name: Deploy

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1

      - run: npm install

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          preCommands: |
            python3 deploy.py
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
